<?php

/**
 * Copy/download asset logo dari upstream cahyadsn/wilayah_logo.
 *
 * Struktur di upstream:
 *   prov/img/<kode>.png      → Logo provinsi full
 *   prov/thumbs/<kode>.png   → Logo provinsi thumbnail
 *   kab/<kode_prov>/img/<kode>.png      → Logo kab/kota full
 *   kab/<kode_prov>/thumbs/<kode>.png   → Logo kab/kota thumbnail
 *
 * Usage:
 *   php copy-assets.php "https://raw.githubusercontent.com/cahyadsn/wilayah_logo/refs/heads/main"
 *   php copy-assets.php /path/to/local/wilayah_logo-main
 */

const UPSTREAM_DEFAULT = 'https://raw.githubusercontent.com/cahyadsn/wilayah_logo/refs/heads/main';
const ASSETS_DIR       = __DIR__ . '/../../assets';

$baseUrl = $argv[1] ?? UPSTREAM_DEFAULT;
$isUrl   = str_starts_with($baseUrl, 'http');

// Kode provinsi Indonesia saat ini (38 provinsi)
$PROV_CODES = [
    '11','12','13','14','15','16','17','18','19',
    '21',
    '31','32','33','34','35','36',
    '51','52','53',
    '61','62','63','64','65',
    '71','72','73','74','75','76',
    '81','82',
    '91','92','93','94','95','96',
];

echo "=== Logo Asset Sync ===\n";
echo "Source: {$baseUrl}\n";
echo "Output: " . ASSETS_DIR . "\n\n";

// Create dir structure
foreach (['prov/img', 'prov/thumbs'] as $dir) {
    @mkdir(ASSETS_DIR . "/{$dir}", 0755, true);
}

$downloaded = 0;
$skipped    = 0;

// ─── Provinsi ───────────────────────────────────────
echo "[prov] Mengunduh logo provinsi...\n";
foreach ($PROV_CODES as $code) {
    foreach (['img', 'thumbs'] as $type) {
        $filename = $type === 'thumbs' ? "{$code}_thumbs.png" : "{$code}.png";
        $src  = "{$baseUrl}/prov/{$type}/{$filename}";
        $dest = ASSETS_DIR . "/prov/{$type}/{$code}.png";

        if (downloadFile($src, $dest, $isUrl)) {
            $downloaded++;
        } else {
            $skipped++;
        }
    }
}

// ─── Kabupaten/Kota ─────────────────────────────────
echo "[kab] Mengunduh logo kabupaten/kota...\n";
foreach ($PROV_CODES as $provCode) {
    @mkdir(ASSETS_DIR . "/kab/{$provCode}/img",    0755, true);
    @mkdir(ASSETS_DIR . "/kab/{$provCode}/thumbs", 0755, true);

    // Coba download semua kab dengan format kode 2 digit provCode + .xx
    // Kab/kota kode format: PP.NN (misal 32.01, 32.02, dst)
    for ($i = 1; $i <= 99; $i++) {
        $kabCode = sprintf('%s.%02d', $provCode, $i);

        foreach (['img', 'thumbs'] as $type) {
            $filename = $type === 'thumbs' ? "{$kabCode}_thumbs.png" : "{$kabCode}.png";
            $src  = "{$baseUrl}/kab/{$provCode}/{$type}/{$filename}";
            $dest = ASSETS_DIR . "/kab/{$provCode}/{$type}/{$kabCode}.png";

            if (downloadFile($src, $dest, $isUrl)) {
                $downloaded++;
            }
        }
    }
}

// ─── Simpan versi hash ──────────────────────────────
$hash = getenv('UPSTREAM_HASH') ?: 'unknown';
file_put_contents(ASSETS_DIR . '/version.txt', $hash);
file_put_contents(
    ASSETS_DIR . '/version.php',
    "<?php\n// Auto-generated by CI/CD. DO NOT EDIT.\nreturn [\n"
    . "    'version' => '" . date('Y.m.d') . "',\n"
    . "    'data_date' => '" . date('Y-m-d') . "',\n"
    . "    'generated_at' => '" . gmdate('c') . "',\n"
    . "    'source_hash' => '{$hash}',\n"
    . "    'source' => [\n"
    . "        'repo' => 'cahyadsn/wilayah_logo',\n"
    . "        'branch' => 'main',\n"
    . "        'hash' => '{$hash}',\n"
    . "    ],\n"
    . "    'downloaded' => {$downloaded},\n"
    . "    'skipped' => {$skipped},\n"
    . "];\n"
);

echo "\n=== Selesai: {$downloaded} logo diunduh, {$skipped} tidak tersedia ===\n";

// ─── Helper ─────────────────────────────────────────
function downloadFile(string $src, string $dest, bool $isUrl): bool
{
    if ($isUrl) {
        $ctx = stream_context_create([
            'http' => [
                'method'  => 'GET',
                'header'  => "User-Agent: aliziodev-logos-sync/1.0\r\n",
                'timeout' => 30,
                'ignore_errors' => true,
            ],
        ]);
        $content = @file_get_contents($src, false, $ctx);

        // Cek HTTP status
        $status = $http_response_header[0] ?? '';
        if (! $content || ! str_contains($status, '200')) {
            return false;
        }

        file_put_contents($dest, $content);
        return true;
    }

        $localSrc = rtrim($src, '/');
        if (! file_exists($localSrc)) return false;

    copy($localSrc, $dest);
    return true;
}
