<?php

const UPSTREAM_DEFAULT = 'https://raw.githubusercontent.com/cahyadsn/wilayah_logo/refs/heads/main';
const BUILD_DIR = __DIR__.'/../../.build';
const STAGING_DIR = BUILD_DIR.'/logos';
const ARCHIVE_PATH = BUILD_DIR.'/wilayah-logos.zip';
const MANIFEST_PATH = __DIR__.'/../../assets/version.php';

$baseUrl = $argv[1] ?? UPSTREAM_DEFAULT;
$isUrl = str_starts_with($baseUrl, 'http');

$PROV_CODES = [
    '11', '12', '13', '14', '15', '16', '17', '18', '19',
    '21',
    '31', '32', '33', '34', '35', '36',
    '51', '52', '53',
    '61', '62', '63', '64', '65',
    '71', '72', '73', '74', '75', '76',
    '81', '82',
    '91', '92', '93', '94', '95', '96',
];

echo "=== Logo Asset Sync ===\n";
echo "Source: {$baseUrl}\n";
echo "Archive: ".ARCHIVE_PATH."\n";
echo "Manifest: ".MANIFEST_PATH."\n\n";

deleteDirectory(BUILD_DIR);
@mkdir(STAGING_DIR.'/prov/img', 0755, true);
@mkdir(STAGING_DIR.'/prov/thumbs', 0755, true);
@mkdir(dirname(MANIFEST_PATH), 0755, true);

$counts = [
    'prov' => 0,
    'kab' => 0,
];

$downloaded = 0;

echo "[prov] Mengunduh logo provinsi...\n";
foreach ($PROV_CODES as $code) {
    foreach (['img', 'thumbs'] as $type) {
        $filename = $type === 'thumbs' ? "{$code}_thumbs.png" : "{$code}.png";
        $src = "{$baseUrl}/prov/{$type}/{$filename}";
        $dest = STAGING_DIR."/prov/{$type}/{$code}.png";

        if (downloadFile($src, $dest, $isUrl)) {
            $downloaded++;
            $counts['prov']++;
        }
    }
}

echo "[kab] Mengunduh logo kabupaten/kota...\n";
foreach ($PROV_CODES as $provCode) {
    @mkdir(STAGING_DIR."/kab/{$provCode}/img", 0755, true);
    @mkdir(STAGING_DIR."/kab/{$provCode}/thumbs", 0755, true);

    for ($i = 1; $i <= 99; $i++) {
        $kabCode = sprintf('%s.%02d', $provCode, $i);

        foreach (['img', 'thumbs'] as $type) {
            $filename = $type === 'thumbs' ? "{$kabCode}_thumbs.png" : "{$kabCode}.png";
            $src = "{$baseUrl}/kab/{$provCode}/{$type}/{$filename}";
            $dest = STAGING_DIR."/kab/{$provCode}/{$type}/{$kabCode}.png";

            if (downloadFile($src, $dest, $isUrl)) {
                $downloaded++;
                $counts['kab']++;
            }
        }
    }
}

$zip = new ZipArchive;
if ($zip->open(ARCHIVE_PATH, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
    fwrite(STDERR, "ERROR: Gagal membuat archive logo di ".ARCHIVE_PATH."\n");
    exit(1);
}

addDirectoryToZip($zip, STAGING_DIR, '');
$zip->close();

$hash = getenv('UPSTREAM_HASH') ?: 'unknown';
file_put_contents(
    MANIFEST_PATH,
    "<?php\n// Auto-generated by CI/CD. DO NOT EDIT.\nreturn [\n"
    . "    'version' => '" . date('Y.m.d') . "',\n"
    . "    'data_date' => '" . date('Y-m-d') . "',\n"
    . "    'generated_at' => '" . gmdate('c') . "',\n"
    . "    'source_hash' => '{$hash}',\n"
    . "    'source' => [\n"
    . "        'repo' => 'cahyadsn/wilayah_logo',\n"
    . "        'branch' => 'main',\n"
    . "        'hash' => '{$hash}',\n"
    . "    ],\n"
    . "    'asset' => [\n"
    . "        'name' => 'wilayah-logos.zip',\n"
    . "        'url' => '',\n"
    . "        'format' => 'zip',\n"
    . "        'size_bytes' => ".(file_exists(ARCHIVE_PATH) ? filesize(ARCHIVE_PATH) : 0).",\n"
    . "    ],\n"
    . "    'counts' => [\n"
    . "        'prov' => {$counts['prov']},\n"
    . "        'kab' => {$counts['kab']},\n"
    . "        'total' => {$downloaded},\n"
    . "    ],\n"
    . "];\n"
);

echo "\n=== Selesai: {$downloaded} logo diunduh ===\n";

function downloadFile(string $src, string $dest, bool $isUrl): bool
{
    if ($isUrl) {
        $ctx = stream_context_create([
            'http' => [
                'method' => 'GET',
                'header' => "User-Agent: aliziodev-logos-sync/1.0\r\n",
                'timeout' => 30,
                'ignore_errors' => true,
            ],
        ]);
        $content = @file_get_contents($src, false, $ctx);
        $status = $http_response_header[0] ?? '';

        if (! $content || ! str_contains($status, '200')) {
            return false;
        }

        file_put_contents($dest, $content);

        return true;
    }

    $localSrc = rtrim($src, '/');
    if (! file_exists($localSrc)) {
        return false;
    }

    copy($localSrc, $dest);

    return true;
}

function addDirectoryToZip(ZipArchive $zip, string $directory, string $prefix): void
{
    $items = scandir($directory);
    if ($items === false) {
        return;
    }

    foreach ($items as $item) {
        if ($item === '.' || $item === '..') {
            continue;
        }

        $sourcePath = $directory.'/'.$item;
        $zipPath = ltrim($prefix.'/'.$item, '/');

        if (is_dir($sourcePath)) {
            $zip->addEmptyDir($zipPath);
            addDirectoryToZip($zip, $sourcePath, $zipPath);
            continue;
        }

        $zip->addFile($sourcePath, $zipPath);
    }
}

function deleteDirectory(string $directory): void
{
    if (! is_dir($directory)) {
        return;
    }

    $items = scandir($directory);
    if ($items === false) {
        return;
    }

    foreach ($items as $item) {
        if ($item === '.' || $item === '..') {
            continue;
        }

        $path = $directory.'/'.$item;

        if (is_dir($path)) {
            deleteDirectory($path);
            continue;
        }

        @unlink($path);
    }

    @rmdir($directory);
}
