<?php
// Auto-generated by CI/CD. DO NOT EDIT.
return [
    'version' => '2026.03.06',
    'data_date' => '2026-03-06',
    'generated_at' => '2026-03-06T23:58:56+00:00',
    'source_hash' => 'unknown',
    'source' => [
        'repo' => 'cahyadsn/wilayah_logo',
        'branch' => 'main',
        'hash' => 'unknown',
    ],
    'asset' => [
        'name' => 'wilayah-logos.zip',
        'url' => '',
        'format' => 'zip',
        'size_bytes' => 233863774,
    ],
    'counts' => [
        'prov' => 76,
        'kab' => 1022,
        'total' => 1098,
    ],
];
